config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :statuses
  resources :levels
  resources :sessions
  resources :stopwatches
  resources :incompletes
  resources :users
  resources :focus_musics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy!

    respond_to do |format|
      format.html { redirect_to statuses_path, status: :see_other, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:description, :created_at, :updated_at)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <%= form.datetime_field :updated_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div id="<%= dom_id status %>">
  <p>
    <strong>Description:</strong>
    <%= status.description %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= status.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= status.updated_at %>
  </p>

</div>

app/views/statuses/edit.html.erb
<% content_for :title, "Editing status" %>

<h1>Editing status</h1>

<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Show this status", @status %> |
  <%= link_to "Back to statuses", statuses_path %>
</div>

app/views/statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Statuses" %>

<h1>Statuses</h1>

<div id="statuses">
  <% @statuses.each do |status| %>
    <%= render status %>
    <p>
      <%= link_to "Show this status", status %>
    </p>
  <% end %>
</div>

<%= link_to "New status", new_status_path %>

app/views/statuses/new.html.erb
<% content_for :title, "New status" %>

<h1>New status</h1>

<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Back to statuses", statuses_path %>
</div>

app/views/statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @status %>

<div>
  <%= link_to "Edit this status", edit_status_path(@status) %> |
  <%= link_to "Back to statuses", statuses_path %>

  <%= button_to "Destroy this status", @status, method: :delete %>
</div>