config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :statuses
  resources :levels
  resources :sessions
  resources :stopwatches
  resources :incompletes
  resources :users
  resources :focus_musics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/focus_music.rb
class FocusMusic < ApplicationRecord
end

app/controllers/focus_musics_controller.rb
class FocusMusicsController < ApplicationController
  before_action :set_focus_music, only: %i[ show edit update destroy ]

  # GET /focus_musics or /focus_musics.json
  def index
    @focus_musics = FocusMusic.all
  end

  # GET /focus_musics/1 or /focus_musics/1.json
  def show
  end

  # GET /focus_musics/new
  def new
    @focus_music = FocusMusic.new
  end

  # GET /focus_musics/1/edit
  def edit
  end

  # POST /focus_musics or /focus_musics.json
  def create
    @focus_music = FocusMusic.new(focus_music_params)

    respond_to do |format|
      if @focus_music.save
        format.html { redirect_to @focus_music, notice: "Focus music was successfully created." }
        format.json { render :show, status: :created, location: @focus_music }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @focus_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /focus_musics/1 or /focus_musics/1.json
  def update
    respond_to do |format|
      if @focus_music.update(focus_music_params)
        format.html { redirect_to @focus_music, notice: "Focus music was successfully updated." }
        format.json { render :show, status: :ok, location: @focus_music }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @focus_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /focus_musics/1 or /focus_musics/1.json
  def destroy
    @focus_music.destroy!

    respond_to do |format|
      format.html { redirect_to focus_musics_path, status: :see_other, notice: "Focus music was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_focus_music
      @focus_music = FocusMusic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def focus_music_params
      params.require(:focus_music).permit(:url)
    end
end

app/helpers/focus_musics_helper.rb
module FocusMusicsHelper
end

app/views/focus_musics/_focus_music.html.erb
<div id="<%= dom_id focus_music %>">
  <p>
    <strong>Url:</strong>
    <%= focus_music.url %>
  </p>

</div>

app/views/focus_musics/_form.html.erb
<%= form_with(model: focus_music) do |form| %>
  <% if focus_music.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(focus_music.errors.count, "error") %> prohibited this focus_music from being saved:</h2>

      <ul>
        <% focus_music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/focus_musics/edit.html.erb
<% content_for :title, "Editing focus music" %>

<h1>Editing focus music</h1>

<%= render "form", focus_music: @focus_music %>

<br>

<div>
  <%= link_to "Show this focus music", @focus_music %> |
  <%= link_to "Back to focus musics", focus_musics_path %>
</div>

app/views/focus_musics/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Focus musics" %>

<h1>Focus musics</h1>

<div id="focus_musics">
  <% @focus_musics.each do |focus_music| %>
    <%= render focus_music %>
    <p>
      <%= link_to "Show this focus music", focus_music %>
    </p>
  <% end %>
</div>

<%= link_to "New focus music", new_focus_music_path %>

app/views/focus_musics/new.html.erb
<% content_for :title, "New focus music" %>

<h1>New focus music</h1>

<%= render "form", focus_music: @focus_music %>

<br>

<div>
  <%= link_to "Back to focus musics", focus_musics_path %>
</div>

app/views/focus_musics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @focus_music %>

<div>
  <%= link_to "Edit this focus music", edit_focus_music_path(@focus_music) %> |
  <%= link_to "Back to focus musics", focus_musics_path %>

  <%= button_to "Destroy this focus music", @focus_music, method: :delete %>
</div>