config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :statuses
  resources :levels
  resources :sessions
  resources :stopwatches
  resources :incompletes
  resources :users
  resources :focus_musics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/stopwatch.rb
class Stopwatch < ApplicationRecord
end

app/controllers/stopwatches_controller.rb
class StopwatchesController < ApplicationController
  before_action :set_stopwatch, only: %i[ show edit update destroy ]

  # GET /stopwatches or /stopwatches.json
  def index
    @stopwatches = Stopwatch.all
  end

  # GET /stopwatches/1 or /stopwatches/1.json
  def show
  end

  # GET /stopwatches/new
  def new
    @stopwatch = Stopwatch.new
  end

  # GET /stopwatches/1/edit
  def edit
  end

  # POST /stopwatches or /stopwatches.json
  def create
    @stopwatch = Stopwatch.new(stopwatch_params)

    respond_to do |format|
      if @stopwatch.save
        format.html { redirect_to @stopwatch, notice: "Stopwatch was successfully created." }
        format.json { render :show, status: :created, location: @stopwatch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stopwatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stopwatches/1 or /stopwatches/1.json
  def update
    respond_to do |format|
      if @stopwatch.update(stopwatch_params)
        format.html { redirect_to @stopwatch, notice: "Stopwatch was successfully updated." }
        format.json { render :show, status: :ok, location: @stopwatch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stopwatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stopwatches/1 or /stopwatches/1.json
  def destroy
    @stopwatch.destroy!

    respond_to do |format|
      format.html { redirect_to stopwatches_path, status: :see_other, notice: "Stopwatch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stopwatch
      @stopwatch = Stopwatch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stopwatch_params
      params.require(:stopwatch).permit(:started_at, :completed_at, :duration)
    end
end

app/helpers/stopwatches_helper.rb
module StopwatchesHelper
end

app/views/stopwatches/_form.html.erb
<%= form_with(model: stopwatch) do |form| %>
  <% if stopwatch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stopwatch.errors.count, "error") %> prohibited this stopwatch from being saved:</h2>

      <ul>
        <% stopwatch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :started_at, style: "display: block" %>
    <%= form.datetime_field :started_at %>
  </div>

  <div>
    <%= form.label :completed_at, style: "display: block" %>
    <%= form.datetime_field :completed_at %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stopwatches/_stopwatch.html.erb
<div id="<%= dom_id stopwatch %>">
  <p>
    <strong>Started at:</strong>
    <%= stopwatch.started_at %>
  </p>

  <p>
    <strong>Completed at:</strong>
    <%= stopwatch.completed_at %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= stopwatch.duration %>
  </p>

</div>

app/views/stopwatches/edit.html.erb
<% content_for :title, "Editing stopwatch" %>

<h1>Editing stopwatch</h1>

<%= render "form", stopwatch: @stopwatch %>

<br>

<div>
  <%= link_to "Show this stopwatch", @stopwatch %> |
  <%= link_to "Back to stopwatches", stopwatches_path %>
</div>

app/views/stopwatches/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Stopwatches" %>

<h1>Stopwatches</h1>

<div id="stopwatches">
  <% @stopwatches.each do |stopwatch| %>
    <%= render stopwatch %>
    <p>
      <%= link_to "Show this stopwatch", stopwatch %>
    </p>
  <% end %>
</div>

<%= link_to "New stopwatch", new_stopwatch_path %>

app/views/stopwatches/new.html.erb
<% content_for :title, "New stopwatch" %>

<h1>New stopwatch</h1>

<%= render "form", stopwatch: @stopwatch %>

<br>

<div>
  <%= link_to "Back to stopwatches", stopwatches_path %>
</div>

app/views/stopwatches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stopwatch %>

<div>
  <%= link_to "Edit this stopwatch", edit_stopwatch_path(@stopwatch) %> |
  <%= link_to "Back to stopwatches", stopwatches_path %>

  <%= button_to "Destroy this stopwatch", @stopwatch, method: :delete %>
</div>